adw-carousel: Fix a -Wmaybe-uninitialized warning
It’s a false positive, but it’s better to be able to compile without
warnings than having to remember which ones are false positives every
time.

```
../../source/libadwaita/src/adw-carousel.c: In function ‘adw_carousel_reorder’:
../../source/libadwaita/src/adw-carousel.c:1324:5: error: ‘next_info’ may be used uninitialized [-Werror=maybe-uninitialized]
 1324 |     gtk_widget_insert_before (child, GTK_WIDGET (self), next_info->widget);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Signed-off-by: Philip Withnall <pwithnall@gnome.org>


(cherry picked from commit 0596955023a171b5656aee71287353092790280c)

(cherry picked from commit 66950aa0f2e1aa9798d28394e1e84a78c82b9ca3)